### ISSUE TITLE
VS Code complains about Sass variables

### ISSUE THREAD

**Issue by mvolkmann** [kaisermann/svelte-preprocess#74] opened 2019-10-12 18:47 UTC
I have a `svelte.config.js` file in the root of my application that contains the following:

```js
const sveltePreprocess = require('svelte-preprocess');

module.exports = {
  preprocess: sveltePreprocess({
    scss: true
  })
};
```

But after restarting VS Code and opening the root directory of the application, I still get a "Selector is expected" warning from ESLint when I open a file that contains the following:

```html
<style lang="scss">
  $color: green;
  ...
</style>
```
Am I missing some required configuration?

**Comment by dkzlv** [comment] 2019-10-19 11:03
Yeah, you should use another `type="text/scss"` instead of `lang="scss"`:

```html
<style type="text/scss">
    ...
</style>
```

**Comment by mvolkmann** [comment] 2019-10-19 14:42
That doesn't stop VS Code from complaining about my use of Sass variables.

**Comment by dkzlv** [comment] 2019-10-20 12:01
Have you installed Svelte extension for VS Code? I'm using [this one](https://marketplace.visualstudio.com/items?itemName=JamesBirtles.svelte-vscode), for example.

BTW, I was wrong, you can actually use `lang="scss"` in your components.

**Comment by mvolkmann** [comment] 2019-10-20 13:31
Yes, I do have that VS Code extension installed.

**Comment by kaisermann** [comment] 2019-10-21 02:17
I've cloned `sveltejs/template`, installed `svelte-preprocess` and `sass`, created a `svelte.config.js` file identical to yours, added some sass code to `App.svelte` using variables and nested selectors and vscode is not complaining about it. Would you be able to provide a sample of your repo?

Here's the template I just mentioned:
[template.tar.gz](https://github.com/kaisermann/svelte-preprocess/files/3748798/template.tar.gz)

**Comment by kaisermann** [comment] 2019-10-26 17:34
Will close this for now, since I was unable to reproduce it. Feel free to open it again if your issue persists 👍

**Closed** 2019-10-26 17:34 UTC
Labels: question

**Comment by mvolkmann** [comment] 2019-10-26 18:06
Thank, it's working for me now!
