### ISSUE TITLE
hot reloading doesn't work on styles "text/sass" with @import

### ISSUE THREAD

**Issue by bugleev** [kaisermann/svelte-preprocess#71] opened 2019-09-27 16:13 UTC
Started here: [rollup-plugin-svelte](https://github.com/rollup/rollup-plugin-svelte/issues/67).
The problem:
I have a component using sass styles with **svelte-preprocess** like this:
``` javascript
<style type="text/sass">
@import "./test.sass"
</style>
 ```
when contents of test.sass are changed in dev mode, styles are not updated in the browser.
Although when i'm not using @import:
``` javascript
<style type="text/sass">
.someClass
  color: red
</style>
 ```
everything works fine.
Any ideas how to resolve this?

**Comment by kaisermann** [comment] 2019-10-29 01:08
Hi @bugleev, sorry for taking so long to get to this. Could you test this behaviour on this project? 
[svelte.zip](https://github.com/kaisermann/svelte-preprocess/files/3781229/svelte.zip). It's just a copy of `sveltejs/template` with `svelte-preprocess` and a `test.sass` file. Running `npm run dev` and saving the `test.sass` file seems to be correctly updating the browser page.

**Comment by kaisermann** [comment] 2019-10-30 20:54
I'm closing this issue since I was unable to reproduce it. Feel free to open it again if your problem persists 👍

**Closed by kaisermann** 2019-10-30 20:54 UTC
Labels: question

**Comment by bugleev** [comment] 2019-10-31 06:07
it worked for me, thanks! Was a problem on my end i guess

**Comment by nitro52** [comment] 2020-01-24 01:41
@kaisermann i'm having this issue with my webpack build. Do you know what part of the config impacts this?

**Comment by kaisermann** [comment] 2020-01-24 01:48
@nitro52 Nope... It helps a lot if you are able to provide a repro 🤓

**Comment by nitro52** [comment] 2020-01-24 01:50
Yeah i couldn't see anything obvious in the rollup config, i'll try to test reproduce on my template project.
