### ISSUE TITLE
Can't make postcss sugarss work II

### ISSUE THREAD

**Issue by zamkevich** [kaisermann/svelte-preprocess#127] opened 2020-03-28 12:48 UTC
I saw issue #43 and tried many ways (from issue #43 too), but still can't make it work.
I created [a repository](https://github.com/zamkevich/Svelte_preprocess_tester--Sugarss_Pug) with a basic config for testing.

**postcss.config.js**
```
module.exports = () => ({
  parser: 'sugarss',
  map: true,
  plugins: {
    'postcss-nested': {},
    …

```
**app.svelte**
```
<style lang="postcss">
  main
    text-align: center
    padding: 1em
    …
```

**terminal**
```
CssSyntaxError: app.svelte:3:3: Unknown word
…
```

**Comment by kaisermann** [comment] 2020-03-29 20:42
Thanks for your report! That was being caused by how the `postcss-load-config` spits the option object. Fixed in `3.7.1` 🎉

**Closed** 2020-03-29 20:42 UTC
