### ISSUE TITLE
Yarn 2.0 Claims: SyntaxError: SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by andrewdc** [kaisermann/svelte-preprocess#112] opened 2020-01-31 21:06 UTC
**Describe the bug**
When running Yarn 2.0.0-rc.27 on a project that included this package, the install fails with:

```
➤ YN0007: │ svelte-preprocess@npm:3.2.6 [a80cd] must be built because it never did before or the last one failed
➤ YN0009: │ svelte-preprocess@npm:3.2.6 [a80cd] couldn't be built successfully (exit code 1, logs can be found here: /var/folders/53/v27mry_j0yjc95t7fwhpcxcmmgc8yl/T/logfile-176008BR68TqNQ3vQ.log)
```

**Logs**
```
# This file contains the result of Yarn building a package (svelte-preprocess@virtual:a80cd58d511507afd8c6096b5996988fa53ff5e758e370dfeeda49e6fcadf647417d79c3d73d4f5a9d30494719c40cbdc11365a9da5f61ed3a3806c43d7ed7ad#npm:3.2.6)
# Script name: postinstall

[eval]:1
console.log('u001b[36mu001b[1m[svelte-preprocess] Don't forget to install the preprocessors packages that will be used: u001b[22mu001b[39mu001b[34mnode-sass/sass, stylus, less, postcss &  postcss-load-config, coffeescript, pug, etc...u001b[0m')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:83:7)
    at createScript (vm.js:277:10)
    at Object.runInThisContext (vm.js:329:10)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at evalScript (internal/bootstrap/node.js:589:27)
    at startup (internal/bootstrap/node.js:265:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**To Reproduce**
This problem appears when running the basic `yarn` install command, with this repo as a dev dependency.

**Expected behavior**
Installation is successful.

**Information about your project:**

- System: `OSX 10.14.6`

- `svelte-preprocess` version: 3.2.6 

- Tooling: `Rollup`

- Package Manager: `Yarn 2.0.0-rc.27`

**Additional context**
This just started after switching to Yarn 2. It's likely more stringent about something. I cloned the project and was going to see if there really is a missing ')' - but it appears it might simply be an escaping problem, given this `u001b` and `u001b[0m` etc.

Also, forgive me if this isn't so helpful. Somehow, this is my first github bug I have logged in 15 years of front-end dev. ;)

**Comment by kaisermann** [comment] 2020-02-01 17:01
This was fixed in 3.3.1. Dupe of #110 😁

**Closed** 2020-02-01 17:01 UTC
